### ISSUE TITLE
Migrate from Mocha to Jest

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2550]
As discussed with @code-asher and @nhooyr, we've decided to migrate from Mocha to Jest as our testing framework of choice for the following reasons:
- Jest has a larger community, more active and more popular in the JS ecosystem
- more members of the team are familiar with it
- built-in support for code coverage

This issue is for transparency and to track the migration.

## TODOS
- [x] Add `jest` and make sure it works ([`ts-jest`](https://github.com/kulshekhar/ts-jest) Is one of the recommended approaches, easy setup)
- [x] Use codemods to migrate mocha tests over ([helpful resource](https://lirantal.medium.com/migrating-a-mocha-project-to-jest-test-framework-76d13d76685))
- [x] Remove mocha fully
- [x] Add code coverage (including shield to `README`)

**Comment by jsjoeio** [comment]
Closing via #2564
